name: release

on:
  push:
    #    branches:
    #      - master
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-20.04-16c-64g
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Sanity Check
        run: |
          cat /proc/cpuinfo

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          caller-workflow-name: test

      - name: Install cargo sort
        run: |
          cargo install cargo-sort

      - name: Cargo sort
        run: cargo sort --workspace --check

      - name: Clippy check
        run: cargo clippy --all-features --all-targets --tests -- -D warnings

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # see https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jitolabs/jito-shredstream-proxy:${{github.ref_name}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64,linux/x86_64

      - name: Copy artifact from container
        run: |
          docker run --rm --platform linux/x86_64 --entrypoint cat jitolabs/jito-shredstream-proxy:${{github.ref_name}} /app/jito-shredstream-proxy > ./jito-shredstream-proxy-x86_64-unknown-linux-gnu
          docker run --rm --platform linux/arm64 --entrypoint cat jitolabs/jito-shredstream-proxy:${{github.ref_name}} /app/jito-shredstream-proxy > ./jito-shredstream-proxy-arm64
          ls -lh .
          file ./jito-shredstream-proxy-x86_64-unknown-linux-gnu
          file ./jito-shredstream-proxy-arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./jito-shredstream-proxy-x86_64-unknown-linux-gnu
            ./jito-shredstream-proxy-arm64
